### ISSUE TITLE
Reject tweets with similar content

### ISSUE THREAD

**Issue by FISHMANPET** [Resisty/HorseFinder#1]
These 4 tweets are functionally identical but were all RTed within a few hours of each other, perhaps there's some string comparison library that cna be used to weed these out?
https://twitter.com/FirePostFeed/status/564877856254091265
https://twitter.com/TiGeyO/status/564877822317965312
https://twitter.com/News_release1/status/564877818849271808
https://twitter.com/TaxAssistIpswic/status/564877810347827200

**Comment by FISHMANPET** [comment]
Perhaps difflib could be used to compare the strings with a relatively low threshold?
https://docs.python.org/2/library/difflib.html

**Comment by Resisty** [comment]
Notes for myself when I'm actually working on this:
- Start storing all tweets that get retweeted
- Check retweet applicants' tweet['text'] against all DB entries' select(Banned.tweetext) with difflib:

```
from difflib import SequenceMatcher
match = SequenceMatcher(None, status['text'], select['text'])
retweet(status) if match.ratio < cutoff else pass
```

**Comment by Resisty** [comment]
This should now be implemented in https://github.com/Resisty/HorseFinder/commit/fa9b34a3ebc01f1c8d4737d4e5d00bfb6f4eb149
